---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 10/02/2021 00:19
---

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1000)
        local ped = PlayerPedId()
        if GetPedArmour(ped) > 0 then
            SetPedArmour(ped,0)
            vPUNISHMENTS.applyPunish({ reason = "Spawn de colete **(SUSPEITA I)**", punishment = "Log", requireScreenshoot = true });
        end
    end
end)