---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 10/02/2021 03:58
---

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1000)
        local count_flags = 0
        local active_players = GetActivePlayers();
        for i = 1,#active_players do
            if i ~= PlayerId() then
                if DoesBlipExist(GetBlipFromEntity(GetPlayerPed(i))) then
                    count_flags = count_flags + 1
                end
            end
            if count_flags > 0 then
                vPUNISHMENTS.applyPunish({ reason = "Blip de jogadores no mapa **(SUSPEITA II)**", punishment = "Log", requireScreenshoot = true });
                break;
            end
        end
    end
end)
