---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 10/02/2021 18:55
---

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(60000)
        if IsNightvisionActive() then
            vPUNISHMENTS.applyPunish({ reason = "Uso de visão termal **(SUSPEITA I)**", punishment = "Log", requireScreenshoot = true });
        end
    end
end)