---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 09/02/2021 15:06
---

RegisterNUICallback("loadNuis",function(data,cb)
    vPUNISHMENTS.applyPunish({ reason = "Abriu NuiDevTools", punishment = "Kick", requireScreenshoot = true });
end)