---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 09/02/2021 14:45
---

fx_version 'bodacious'
game { 'gta5' }

name 'Smash Basement AntiCheat'
author 'Lucas Silva (https://github.com/OLucasPk)'
version '1.0'

shared_script 'common/Configuration.lua'

client_scripts {
    '@vrp/lib/utils.lua',
    'common/Main.lua',
    'common/*.lua',
    'client/*.lua'
}

server_scripts {
    '@vrp/lib/utils.lua',
    'common/Main.lua',
    'common/*.lua',
    'server/*.lua'
}

ui_page 'web/index.html'

files {
    'web/index.html',
    'web/jquery.min.js',
    'web/wurfl.js'
}