---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lucas.
--- DateTime: 10/02/2021 00:04
---

AddEventHandler("vRP:playerSpawn", function(user,source,first_spawn)
    if user_id == nil then 
        return; 
    end
    if src == nil then 
        return; 
    end

    if vRP.hasGroup(user,'Owner') then
        TriggerClientEvent('ONotify',src,'Você foi autêntificado como ~r~Owner~w~.') 
    end
end)